#!/usr/bin/env bash
# DAST stack for the OWASP ZAP baseline scan (task 15.1, design D16), shared
# by the `dast-zap` CI job and `pnpm ci:local`.
#
#   dast.sh up     PostgreSQL 16 behind verified TLS, migrations, apps/api
#                  (main.ts) and one seeded organization and session
#   dast.sh scan   the ZAP baseline scan, with the same image and command
#                  the pinned zaproxy/action-baseline runs in CI
#   dast.sh api-scan
#                  a passive ZAP API scan of every catalog OpenAPI operation
#   dast.sh down   stops the API and the database
#   dast.sh all    up, scan, api-scan and down (the local equivalent of the CI job)
#
# The database keeps design D5's rule: every connection uses
# `sslmode=verify-full`. Each run generates a throwaway CA and a `localhost`
# server certificate, so nothing here relaxes TLS. The database password and
# BETTER_AUTH_SECRET are random per run and never printed; the session
# cookie reaches ZAP only through ZAP_AUTH_HEADER_VALUE (masked in CI).
#
# Cerbos must already be running (CI starts the pinned image; locally,
# scripts/dev/start-cerbos.sh or the SessionStart hook does).

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"

# postgres:16, pinned by digest like the CI test services (task 24.9).
PG_IMAGE="${DAST_PG_IMAGE:-postgres:16@sha256:1a6ab3f5345eb6dbe04a1349529caabdb0ab09293a09590fad07b2246bfa4b54}"
# ghcr.io/zaproxy/zaproxy:stable, pinned by digest like the Cerbos image.
ZAP_IMAGE="${DAST_ZAP_IMAGE:-ghcr.io/zaproxy/zaproxy@sha256:781a2bdaea47324e7bab583e2263f21d257b0aee61ed51521a5be45f5f5081ef}"
PG_CONTAINER="tayzu-dast-postgres"
PG_PORT="${DAST_PG_PORT:-5433}"
API_PORT="${DAST_API_PORT:-3000}"
CERBOS_ADDRESS="${CERBOS_ADDRESS:-localhost:3593}"
CERBOS_HEALTH_URL="${DAST_CERBOS_HEALTH_URL:-http://localhost:3592/_cerbos/health}"
STATE_DIR="${DAST_STATE_DIR:-${RUNNER_TEMP:-/tmp}/tayzu-dast}"
# Relative to the repository root, and to /zap/wrk inside the ZAP container.
RULES_FILE=".zap/rules.tsv"
# The catalog contract, generated by `pnpm contract:generate`.
OPENAPI_FILE="openapi/catalog.openapi.json"

log() {
  echo "dast: $*"
}

fail() {
  echo "dast: $*" >&2
  exit 1
}

# Hides a generated value from GitHub Actions logs. A no-op elsewhere.
mask() {
  if [ "${GITHUB_ACTIONS:-}" = "true" ]; then
    echo "::add-mask::$1"
  fi
}

# Retries a command once per second; returns 1 when it never succeeds.
wait_for() {
  local attempts="$1"
  shift
  for _ in $(seq 1 "$attempts"); do
    if "$@" >/dev/null 2>&1; then
      return 0
    fi
    sleep 1
  done
  return 1
}

# A CA and a server certificate for `localhost` and 127.0.0.1, valid one day.
generate_tls() {
  local dir="$STATE_DIR/tls"
  mkdir -p "$dir"
  openssl req -x509 -newkey rsa:2048 -nodes -days 1 -subj "/CN=tayzu-dast-ca" \
    -addext "basicConstraints=critical,CA:TRUE" \
    -addext "keyUsage=critical,keyCertSign,cRLSign" \
    -keyout "$dir/ca.key" -out "$dir/ca.crt" 2>/dev/null
  openssl req -newkey rsa:2048 -nodes -subj "/CN=localhost" \
    -keyout "$dir/server.key" -out "$dir/server.csr" 2>/dev/null
  printf '%s\n' \
    "basicConstraints=CA:FALSE" \
    "keyUsage=critical,digitalSignature,keyEncipherment" \
    "extendedKeyUsage=serverAuth" \
    "subjectAltName=DNS:localhost,IP:127.0.0.1" >"$dir/server.ext"
  openssl x509 -req -in "$dir/server.csr" -CA "$dir/ca.crt" -CAkey "$dir/ca.key" \
    -CAcreateserial -days 1 -extfile "$dir/server.ext" -out "$dir/server.crt" 2>/dev/null
  rm -f "$dir/ca.key" "$dir/server.csr" "$dir/server.ext" "$dir/ca.srl"
}

# PostgreSQL 16 with ssl=on. The key is copied inside the container so it is
# owned by the postgres user with mode 0600, which the server requires.
start_postgres() {
  local password="$1"
  docker rm -f "$PG_CONTAINER" >/dev/null 2>&1 || true
  docker run -d --name "$PG_CONTAINER" \
    -e POSTGRES_USER=tayzu \
    -e POSTGRES_PASSWORD="$password" \
    -e POSTGRES_DB=tayzu_dast \
    -p "127.0.0.1:$PG_PORT:5432" \
    -v "$STATE_DIR/tls:/tls-source:ro" \
    --entrypoint bash \
    "$PG_IMAGE" \
    -c 'install -d -o postgres -g postgres -m 0700 /tls &&
        install -o postgres -g postgres -m 0600 /tls-source/server.crt /tls-source/server.key /tls/ &&
        exec docker-entrypoint.sh postgres -c ssl=on \
          -c ssl_cert_file=/tls/server.crt -c ssl_key_file=/tls/server.key' \
    >/dev/null
}

postgres_accepts_tls() {
  # `pg_isready` inside the container only proves the socket is up; this
  # proves a verified TLS handshake from the host, as the API will make it.
  (cd "$REPO_ROOT/packages/db" && node --input-type=module -e "
    import pg from 'pg';
    const client = new pg.Client({ connectionString: process.env.DATABASE_URL });
    await client.connect();
    await client.query('select 1');
    await client.end();
  ")
}

up() {
  command -v openssl >/dev/null || fail "openssl is required"
  curl -sf "$CERBOS_HEALTH_URL" >/dev/null ||
    fail "Cerbos is not healthy at $CERBOS_HEALTH_URL (start it first)"

  rm -rf "$STATE_DIR"
  mkdir -p "$STATE_DIR"
  chmod 700 "$STATE_DIR"

  local password app_password auth_password secret database_url tls
  password="$(openssl rand -hex 24)"
  app_password="$(openssl rand -hex 24)"
  auth_password="$(openssl rand -hex 24)"
  secret="$(openssl rand -hex 32)"
  mask "$password"
  mask "$app_password"
  mask "$auth_password"
  mask "$secret"

  generate_tls
  start_postgres "$password"
  tls="sslmode=verify-full&sslrootcert=${STATE_DIR}/tls/ca.crt"
  # The owner (the image's superuser) only migrates; the API runs as the
  # runtime roles, so RLS and the role split are exercised (task 24.9).
  database_url="postgres://tayzu:${password}@localhost:${PG_PORT}/tayzu_dast?${tls}"

  export DATABASE_URL="$database_url"
  export BETTER_AUTH_SECRET="$secret"
  # Q40: https outside test. The scan reaches the listener over plain HTTP on
  # localhost; the configured origin only drives cookie and origin settings.
  export BETTER_AUTH_URL="https://localhost:${API_PORT}"
  # Q56: https origins only outside test. The seed sends this Origin, as a
  # browser on the https front end would.
  export ALLOWED_ORIGINS="https://localhost:${API_PORT}"
  export ZAP_SEED_ORIGIN="https://localhost:${API_PORT}"
  export CERBOS_ADDRESS
  export PORT="$API_PORT"
  export HOST="127.0.0.1"
  export ZAP_TARGET_URL="http://localhost:${API_PORT}"
  # Q41: an explicit opt-out; the throwaway stack has no OTLP collector.
  export TAYZU_TELEMETRY_DISABLED="true"
  # Q96: no email provider in the throwaway stack.
  export EMAIL_PROVIDER=none

  log "waiting for PostgreSQL (verified TLS)"
  wait_for 60 postgres_accepts_tls || fail "PostgreSQL did not accept a verified TLS connection in time"

  log "applying migrations"
  (cd "$REPO_ROOT" && pnpm db:migrate)

  # The migrations create tayzu_app and tayzu_auth without a password
  # (design D15); this throwaway database gives them random ones, over the
  # container's local socket, never on a command line.
  printf "ALTER ROLE tayzu_app PASSWORD '%s';\nALTER ROLE tayzu_auth PASSWORD '%s';\n" \
    "$app_password" "$auth_password" |
    docker exec -i "$PG_CONTAINER" psql -q -v ON_ERROR_STOP=1 -U tayzu -d tayzu_dast >/dev/null
  export DATABASE_URL="postgres://tayzu_app:${app_password}@localhost:${PG_PORT}/tayzu_dast?${tls}"
  export AUTH_DATABASE_URL="postgres://tayzu_auth:${auth_password}@localhost:${PG_PORT}/tayzu_dast?${tls}"

  log "starting apps/api"
  # Its own session, so `down` can stop pnpm and the API it starts together.
  setsid nohup pnpm --dir "$REPO_ROOT" --filter @tayzu/api start \
    </dev/null >"$STATE_DIR/api.log" 2>&1 &
  echo $! >"$STATE_DIR/api.pid"
  if ! wait_for 60 curl -sf "http://localhost:${API_PORT}/healthz"; then
    tail -n 50 "$STATE_DIR/api.log" >&2 || true
    fail "apps/api did not become healthy in time"
  fi

  log "seeding an organization and a session"
  # The bootstrap CLI holds both runtime roles: DATABASE_URL (tayzu_app) and
  # AUTH_DATABASE_URL (tayzu_auth), with a fixed CI operator id (Q116).
  (cd "$REPO_ROOT" && TAYZU_OPERATOR_ID="ci:zap-seed" ZAP_ENV_FILE="$STATE_DIR/zap.env" \
    ZAP_TOTP_SECRET_FILE="$STATE_DIR/totp.secret" pnpm exec tsx scripts/ci/zap-seed.ts)
  # What `api-scan` needs to renew the step-up in a later CI step.
  printf '%s\n' "ZAP_TARGET_URL=$ZAP_TARGET_URL" "ZAP_SEED_ORIGIN=$ZAP_SEED_ORIGIN" \
    >"$STATE_DIR/seed.env"
  if [ -n "${GITHUB_ENV:-}" ]; then
    cat "$STATE_DIR/zap.env" >>"$GITHUB_ENV"
  fi
  log "stack is up at http://localhost:${API_PORT}"
}

# Loads the seeded session header and prepares ZAP's work directory.
prepare_zap() {
  local env_file="$STATE_DIR/zap.env"
  [ -f "$env_file" ] || fail "run 'dast.sh up' first (no seeded session)"
  ZAP_WORK="$STATE_DIR/zap"
  mkdir -p "$ZAP_WORK/.zap"
  # Same relative path as in CI, where the action mounts the workspace.
  cp "$REPO_ROOT/$RULES_FILE" "$ZAP_WORK/$RULES_FILE"
  cp "$REPO_ROOT/$OPENAPI_FILE" "$ZAP_WORK/catalog.openapi.json"
  chmod -R a+rwX "$ZAP_WORK"

  # KEY=value lines in the GITHUB_ENV format. A cookie header holds `; `, so
  # the file is parsed, never sourced.
  local line
  while IFS= read -r line; do
    case "$line" in
      ZAP_AUTH_HEADER=* | ZAP_AUTH_HEADER_VALUE=*) export "${line%%=*}=${line#*=}" ;;
    esac
  done <"$env_file"
  export ZAP_AUTH_HEADER_SITE="localhost"

  # zap-*.py first install the beta passive rules from the ZAP marketplace,
  # as in CI; where the marketplace is unreachable (a sandbox with a
  # restrictive network policy), ZAP runs its bundled rules only.
  # A digest-pinned image already present locally is the same image.
  docker pull -q "$ZAP_IMAGE" >/dev/null 2>&1 || docker image inspect "$ZAP_IMAGE" >/dev/null ||
    fail "cannot pull $ZAP_IMAGE"
}

# Runs one ZAP script; exit 1 = a FAIL alert, 2 = a WARN alert, 3 = the scan
# failed. The CI action (fail_action: true) fails the job on 1 and 2, and so
# does this.
run_zap() {
  local name="$1"
  shift
  local code=0
  docker run --rm -v "$ZAP_WORK:/zap/wrk/:rw" --network=host \
    -e ZAP_AUTH_HEADER -e ZAP_AUTH_HEADER_VALUE -e ZAP_AUTH_HEADER_SITE \
    "$ZAP_IMAGE" "$@" -c "$RULES_FILE" || code=$?
  case "$code" in
    0) log "ZAP $name passed (reports in $ZAP_WORK)" ;;
    1 | 2) fail "ZAP $name found alerts (exit $code, reports in $ZAP_WORK)" ;;
    *) fail "ZAP $name could not run (exit $code)" ;;
  esac
}

# The baseline scan, as the pinned zaproxy/action-baseline runs it in CI.
scan() {
  prepare_zap
  run_zap "baseline scan" zap-baseline.py -t "http://localhost:${API_PORT}" \
    -J report_json.json -w report_md.md -r report_html.html
}

# Task 24.9: every operation of the catalog OpenAPI document, requested with
# the seeded MFA session and passively scanned. `-S` (safe mode) skips the
# active scan: D16 is a passive scan, and active DAST belongs to `022`.
#
# Task 28.3 (design Q82): oRPC's CSRF header is added to every request by a
# ZAP replacer rule, so mutating operations reach their handlers instead of
# the CSRF refusal, and the seeded session's MFA step-up is renewed first,
# so `x-tayzu-risk: high` operations run too.
api_scan() {
  prepare_zap
  local line
  while IFS= read -r line; do
    export "${line%%=*}=${line#*=}"
  done <"$STATE_DIR/seed.env"
  (cd "$REPO_ROOT" && ZAP_TOTP_SECRET_FILE="$STATE_DIR/totp.secret" \
    DATABASE_URL=unused BETTER_AUTH_SECRET=unused \
    pnpm exec tsx scripts/ci/zap-seed.ts --refresh)
  local csrf="-config replacer.full_list(0).description=csrf"
  csrf+=" -config replacer.full_list(0).enabled=true"
  csrf+=" -config replacer.full_list(0).matchtype=REQ_HEADER"
  csrf+=" -config replacer.full_list(0).matchstr=x-csrf-token"
  csrf+=" -config replacer.full_list(0).regex=false"
  csrf+=" -config replacer.full_list(0).replacement=orpc"
  run_zap "API scan" zap-api-scan.py -t catalog.openapi.json -f openapi -S \
    -O "http://localhost:${API_PORT}" -z "$csrf" \
    -J api_report_json.json -w api_report_md.md -r api_report_html.html
}

down() {
  if [ -f "$STATE_DIR/api.pid" ]; then
    local pid
    pid="$(cat "$STATE_DIR/api.pid")"
    kill -TERM -- "-$pid" 2>/dev/null || kill -TERM "$pid" 2>/dev/null || true
    rm -f "$STATE_DIR/api.pid"
  fi
  docker rm -f "$PG_CONTAINER" >/dev/null 2>&1 || true
  log "stack stopped"
}

# `pnpm ci:local` counts exit 77 as an explicit SKIP (scripts/ci/local.sh).
if ! docker info >/dev/null 2>&1; then
  echo "dast: docker is not available; the DAST stack cannot run here" >&2
  exit 77
fi

case "${1:-}" in
  up) up ;;
  scan) scan ;;
  api-scan) api_scan ;;
  down) down ;;
  all)
    trap down EXIT
    up
    scan
    api_scan
    ;;
  *)
    echo "usage: dast.sh up|scan|api-scan|down|all" >&2
    exit 2
    ;;
esac
